# Generated by Django 3.0.4 on 2020-03-16 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=254, unique=True, verbose_name='问题')),
                ('answer', models.CharField(max_length=32, unique=True, verbose_name='正确答案')),
                ('sub_score', models.BigIntegerField(verbose_name='本题分数')),
                ('sub_type', models.SmallIntegerField(choices=[(0, '单选'), (1, '多选')], default=1, verbose_name='题目选项类型')),
            ],
            options={
                'verbose_name': '题目表',
                'verbose_name_plural': '题目表',
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='题目类型')),
            ],
        ),
        migrations.CreateModel(
            name='SubOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=128, verbose_name='选项具体内容')),
                ('sub_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject')),
            ],
            options={
                'verbose_name': '选项表',
                'verbose_name_plural': '选项表',
                'db_table': 'sub_options',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.SubType', verbose_name='题目类型'),
        ),
    ]
